spring.application.name=user-service
server.port=8081

# Config Server
spring.config.import=optional:configserver:http://localhost:8888

# Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.prefer-ip-address=true
eureka.instance.lease-renewal-interval-in-seconds=5
eureka.instance.lease-expiration-duration-in-seconds=15

# Actuator
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.profiles.active=default

app.jwt.secret=iqPIlntuYW0IYZPddzI11rAQW7MiFDOAoho4RtjTn20=
app.jwt.expiration-ms=86400000



